package Bloonix::Plugin::CCodes;

use strict;
use warnings;

sub new {
    return bless {}, shift;
}

sub country {
    return [
        { value => "AD", name => "AD - Andorra" },
        { value => "AE", name => "AE - United Arab Emirates" },
        { value => "AF", name => "AF - Afghanistan" },
        { value => "AG", name => "AG - Antigua and Barbuda" },
        { value => "AI", name => "AI - Anguilla" },
        { value => "AL", name => "AL - Albania" },
        { value => "AM", name => "AM - Armenia" },
        { value => "AO", name => "AO - Angola" },
        { value => "AR", name => "AR - Argentina" },
        { value => "AS", name => "AS - American Samoa" },
        { value => "AT", name => "AT - Austria" },
        { value => "AU", name => "AU - Australia" },
        { value => "AW", name => "AW - Aruba" },
        { value => "AX", name => "AX - Aland Islands" },
        { value => "AZ", name => "AZ - Azerbaijan" },
        { value => "BA", name => "BA - Bosnia and Herzegovina" },
        { value => "BB", name => "BB - Barbados" },
        { value => "BD", name => "BD - Bangladesh" },
        { value => "BE", name => "BE - Belgium" },
        { value => "BF", name => "BF - Burkina Faso" },
        { value => "BG", name => "BG - Bulgaria" },
        { value => "BH", name => "BH - Bahrain" },
        { value => "BI", name => "BI - Burundi" },
        { value => "BJ", name => "BJ - Benin" },
        { value => "BL", name => "BL - Saint Barthelemy" },
        { value => "BN", name => "BN - Brunei Darussalam" },
        { value => "BO", name => "BO - Bolivia" },
        { value => "BM", name => "BM - Bermuda" },
        { value => "BQ", name => "BQ - Bonaire, Saint Eustatius and Saba" },
        { value => "BR", name => "BR - Brazil" },
        { value => "BS", name => "BS - The Bahamas" },
        { value => "BT", name => "BT - Bhutan" },
        { value => "BV", name => "BV - Bouvet Island" },
        { value => "BW", name => "BW - Botswana" },
        { value => "BY", name => "BY - Belarus" },
        { value => "BZ", name => "BZ - Belize" },
        { value => "CA", name => "CA - Canada" },
        { value => "CC", name => "CC - Cocos (Keeling) Islands" },
        { value => "CD", name => "CD - Democratic Republic of the Congo" },
        { value => "CF", name => "CF - Central African Republic" },
        { value => "CG", name => "CG - Republic of the Congo" },
        { value => "CH", name => "CH - Switzerland" },
        { value => "CI", name => "CI - Côte d'Ivoire" },
        { value => "CK", name => "CK - Cook Islands" },
        { value => "CL", name => "CL - Chile" },
        { value => "CM", name => "CM - Cameroon" },
        { value => "CN", name => "CN - China" },
        { value => "CO", name => "CO - Colombia" },
        { value => "CR", name => "CR - Costa Rica" },
        { value => "CU", name => "CU - Cuba" },
        { value => "CV", name => "CV - Cape Verde" },
        { value => "CW", name => "CW - Curaçao" },
        { value => "CX", name => "CX - Christmas Island" },
        { value => "CY", name => "CY - Cyprus" },
        { value => "CZ", name => "CZ - Czech Republic" },
        { value => "DE", name => "DE - Germany" },
        { value => "DJ", name => "DJ - Djibouti" },
        { value => "DK", name => "DK - Denmark" },
        { value => "DM", name => "DM - Dominica" },
        { value => "DO", name => "DO - Dominican Republic" },
        { value => "DZ", name => "DZ - Algeria" },
        { value => "EC", name => "EC - Ecuador" },
        { value => "EG", name => "EG - Egypt" },
        { value => "EE", name => "EE - Estonia" },
        { value => "EH", name => "EH - Western Sahara" },
        { value => "ER", name => "ER - Eritrea" },
        { value => "ES", name => "ES - Spain" },
        { value => "ET", name => "ET - Ethiopia" },
        { value => "FI", name => "FI - Finland" },
        { value => "FJ", name => "FJ - Fiji" },
        { value => "FK", name => "FK - Falkland Islands" },
        { value => "FM", name => "FM - Federated States of Micronesia" },
        { value => "FO", name => "FO - Faroe Islands" },
        { value => "FR", name => "FR - France" },
        { value => "GA", name => "GA - Gabon" },
        { value => "GB", name => "GB - United Kingdom" },
        { value => "GE", name => "GE - Georgia" },
        { value => "GD", name => "GD - Grenada" },
        { value => "GF", name => "GF - French Guiana" },
        { value => "GG", name => "GG - Guernsey" },
        { value => "GH", name => "GH - Ghana" },
        { value => "GI", name => "GI - Gibraltar" },
        { value => "GL", name => "GL - Greenland" },
        { value => "GM", name => "GM - Gambia" },
        { value => "GN", name => "GN - Guinea" },
        { value => "GO", name => "GO - Glorioso Islands" },
        { value => "GP", name => "GP - Guadeloupe" },
        { value => "GQ", name => "GQ - Equatorial Guinea" },
        { value => "GR", name => "GR - Greece" },
        { value => "GS", name => "GS - South Georgia and South Sandwich Islands" },
        { value => "GT", name => "GT - Guatemala" },
        { value => "GU", name => "GU - Guam" },
        { value => "GW", name => "GW - Guinea Bissau" },
        { value => "GY", name => "GY - Guyana" },
        { value => "HK", name => "HK - Hong Kong S.A.R." },
        { value => "HM", name => "HM - Heard Island and McDonald Islands" },
        { value => "HN", name => "HN - Honduras" },
        { value => "HR", name => "HR - Croatia" },
        { value => "HT", name => "HT - Haiti" },
        { value => "HU", name => "HU - Hungary" },
        { value => "ID", name => "ID - Indonesia" },
        { value => "IE", name => "IE - Ireland" },
        { value => "IL", name => "IL - Israel" },
        { value => "IM", name => "IM - Isle of Man" },
        { value => "IN", name => "IN - India" },
        { value => "IO", name => "IO - British Indian Ocean Territory" },
        { value => "IQ", name => "IQ - Iraq" },
        { value => "IR", name => "IR - Iran" },
        { value => "IS", name => "IS - Iceland" },
        { value => "IT", name => "IT - Italy" },
        { value => "JE", name => "JE - Jersey" },
        { value => "JM", name => "JM - Jamaica" },
        { value => "JO", name => "JO - Jordan" },
        { value => "JP", name => "JP - Japan" },
        { value => "JU", name => "JU - Juan De Nova Island" },
        { value => "KE", name => "KE - Kenya" },
        { value => "KG", name => "KG - Kyrgyzstan" },
        { value => "KH", name => "KH - Cambodia" },
        { value => "KI", name => "KI - Kiribati" },
        { value => "KM", name => "KM - Comoros" },
        { value => "KN", name => "KN - Saint Kitts and Nevis" },
        { value => "KP", name => "KP - North Korea" },
        { value => "KR", name => "KR - South Korea" },
        { value => "XK", name => "XK - Kosovo" },
        { value => "KW", name => "KW - Kuwait" },
        { value => "KY", name => "KY - Cayman Islands" },
        { value => "KZ", name => "KZ - Kazakhstan" },
        { value => "LA", name => "LA - Lao People's Democratic Republic" },
        { value => "LB", name => "LB - Lebanon" },
        { value => "LC", name => "LC - Saint Lucia" },
        { value => "LI", name => "LI - Liechtenstein" },
        { value => "LK", name => "LK - Sri Lanka" },
        { value => "LR", name => "LR - Liberia" },
        { value => "LS", name => "LS - Lesotho" },
        { value => "LT", name => "LT - Lithuania" },
        { value => "LU", name => "LU - Luxembourg" },
        { value => "LV", name => "LV - Latvia" },
        { value => "LY", name => "LY - Libya" },
        { value => "MA", name => "MA - Morocco" },
        { value => "MC", name => "MC - Monaco" },
        { value => "MD", name => "MD - Moldova" },
        { value => "MG", name => "MG - Madagascar" },
        { value => "ME", name => "ME - Montenegro" },
        { value => "MF", name => "MF - Saint Martin" },
        { value => "MH", name => "MH - Marshall Islands" },
        { value => "MK", name => "MK - Macedonia" },
        { value => "ML", name => "ML - Mali" },
        { value => "MO", name => "MO - Macau S.A.R" },
        { value => "MM", name => "MM - Myanmar" },
        { value => "MN", name => "MN - Mongolia" },
        { value => "MP", name => "MP - Northern Mariana Islands" },
        { value => "MQ", name => "MQ - Martinique" },
        { value => "MR", name => "MR - Mauritania" },
        { value => "MS", name => "MS - Montserrat" },
        { value => "MT", name => "MT - Malta" },
        { value => "MU", name => "MU - Mauritius" },
        { value => "MV", name => "MV - Maldives" },
        { value => "MW", name => "MW - Malawi" },
        { value => "MX", name => "MX - Mexico" },
        { value => "MY", name => "MY - Malaysia" },
        { value => "MZ", name => "MZ - Mozambique" },
        { value => "NA", name => "NA - Namibia" },
        { value => "NC", name => "NC - New Caledonia" },
        { value => "NE", name => "NE - Niger" },
        { value => "NF", name => "NF - Norfolk Island" },
        { value => "NG", name => "NG - Nigeria" },
        { value => "NI", name => "NI - Nicaragua" },
        { value => "NL", name => "NL - Netherlands" },
        { value => "NO", name => "NO - Norway" },
        { value => "NP", name => "NP - Nepal" },
        { value => "NR", name => "NR - Nauru" },
        { value => "NU", name => "NU - Niue" },
        { value => "NZ", name => "NZ - New Zealand" },
        { value => "OM", name => "OM - Oman" },
        { value => "PA", name => "PA - Panama" },
        { value => "PE", name => "PE - Peru" },
        { value => "PF", name => "PF - French Polynesia" },
        { value => "PG", name => "PG - Papua New Guinea" },
        { value => "PH", name => "PH - Philippines" },
        { value => "PK", name => "PK - Pakistan" },
        { value => "PL", name => "PL - Poland" },
        { value => "PM", name => "PM - Saint Pierre and Miquelon" },
        { value => "PN", name => "PN - Pitcairn Islands" },
        { value => "PR", name => "PR - Puerto Rico" },
        { value => "PS", name => "PS - Palestinian Territories" },
        { value => "PT", name => "PT - Portugal" },
        { value => "PW", name => "PW - Palau" },
        { value => "PY", name => "PY - Paraguay" },
        { value => "QA", name => "QA - Qatar" },
        { value => "RE", name => "RE - Reunion" },
        { value => "RO", name => "RO - Romania" },
        { value => "RS", name => "RS - Serbia" },
        { value => "RU", name => "RU - Russia" },
        { value => "RW", name => "RW - Rwanda" },
        { value => "SA", name => "SA - Saudi Arabia" },
        { value => "SB", name => "SB - Solomon Islands" },
        { value => "SC", name => "SC - Seychelles" },
        { value => "SD", name => "SD - Sudan" },
        { value => "SE", name => "SE - Sweden" },
        { value => "SG", name => "SG - Singapore" },
        { value => "SH", name => "SH - Saint Helena" },
        { value => "SI", name => "SI - Slovenia" },
        { value => "SJ", name => "SJ - Svalbard and Jan Mayen" },
        { value => "SK", name => "SK - Slovakia" },
        { value => "SL", name => "SL - Sierra Leone" },
        { value => "SM", name => "SM - San Marino" },
        { value => "SN", name => "SN - Senegal" },
        { value => "SO", name => "SO - Somalia" },
        { value => "SR", name => "SR - Suriname" },
        { value => "SS", name => "SS - South Sudan" },
        { value => "ST", name => "ST - Sao Tome and Principe" },
        { value => "SV", name => "SV - El Salvador" },
        { value => "SX", name => "SX - Sint Maarten" },
        { value => "SY", name => "SY - Syria" },
        { value => "SZ", name => "SZ - Swaziland" },
        { value => "TC", name => "TC - Turks and Caicos Islands" },
        { value => "TD", name => "TD - Chad" },
        { value => "TF", name => "TF - French Southern and Antarctic Lands" },
        { value => "TG", name => "TG - Togo" },
        { value => "TH", name => "TH - Thailand" },
        { value => "TJ", name => "TJ - Tajikistan" },
        { value => "TK", name => "TK - Tokelau" },
        { value => "TL", name => "TL - Timor-Leste" },
        { value => "TM", name => "TM - Turkmenistan" },
        { value => "TN", name => "TN - Tunisia" },
        { value => "TO", name => "TO - Tonga" },
        { value => "TR", name => "TR - Turkey" },
        { value => "TT", name => "TT - Trinidad and Tobago" },
        { value => "TV", name => "TV - Tuvalu" },
        { value => "TW", name => "TW - Taiwan" },
        { value => "TZ", name => "TZ - Tanzania" },
        { value => "UA", name => "UA - Ukraine" },
        { value => "UG", name => "UG - Uganda" },
        { value => "UM-86", name => "UM-86 - Jarvis Island" },
        { value => "UM-81", name => "UM-81 - Baker Island" },
        { value => "UM-84", name => "UM-84 - Howland Island" },
        { value => "UM-67", name => "UM-67 - Johnston Atoll" },
        { value => "UM-71", name => "UM-71 - Midway Islands" },
        { value => "UM-79", name => "UM-79 - Wake Island" },
        { value => "US", name => "US - United States of America" },
        { value => "UY", name => "UY - Uruguay" },
        { value => "UZ", name => "UZ - Uzbekistan" },
        { value => "VA", name => "VA - Vatican City" },
        { value => "VC", name => "VC - Saint Vincent and the Grenadines" },
        { value => "VE", name => "VE - Venezuela" },
        { value => "VG", name => "VG - British Virgin Islands" },
        { value => "VI", name => "VI - US Virgin Islands" },
        { value => "VN", name => "VN - Vietnam" },
        { value => "VU", name => "VU - Vanuatu" },
        { value => "WF", name => "WF - Wallis and Futuna" },
        { value => "WS", name => "WS - Samoa" },
        { value => "YE", name => "YE - Yemen" },
        { value => "YT", name => "YT - Mayotte" },
        { value => "ZA", name => "ZA - South Africa" },
        { value => "ZM", name => "ZM - Zambia" },
        { value => "ZW", name => "ZW - Zimbabwe" }
    ];
}

sub continent {
    return [
        { value => "NA", name => "North America"},
        { value => "SA", name => "South America"},
        { value => "AN", name => "Antarctica"},
        { value => "AF", name => "Africa"},
        { value => "EU", name => "Europe"},
        { value => "AS", name => "Asia"},
        { value => "OC", name => "Oceania"}
    ];
}

1;
