#!/bin/bash

HOST=$1

if test -z "$HOST" ; then
    echo ""
    echo "Usage: $0 <hostname>"
    echo ""
    echo "The hostname is the host and port number of elasticsearch."
    echo ""
    echo "Example: $0 localhost:9200"
    echo ""
    exit 1
fi

TEMPLATE=$(cat /srv/bloonix/webgui/schema/es-template.json)

if test "$1" = "get-template" ; then
    echo "$TEMPLATE"
    exit
fi

curl -XPUT "http://$HOST/_template/template_bloonix/" -d "$TEMPLATE"
echo
